package holdem-solver:host;

interface game-manager {
  enum board-state { flop, turn, river }
  enum wit-game-status { oop-action, ip-action, chance, terminal }

  type wit-card = u32;
  /// Rust の `Action` に対応する variant
  variant wit-action {
    none,
    fold,
    check,
    call,
    bet(u32),
    raise(u32),
    all-in(u32),
    chance( wit-card ),
  }

  variant wit-street {
    flop,
    turn,
    river,
  }

  record wit-action-ratio {
    action: wit-action,
    ratio: f32,
  }

  record wit-action-history-detail {
    action-ratio-list: list<wit-action-ratio>,
    game-status: wit-game-status,
    pot: u32,
    opponent-bet-size: option<u32>,
    street: wit-street,
  }

  record wit-strategy {
    weight: f32,
    action-ratio: f32,
  }
  record wit-strategy-map {
    hand: string,
    action: wit-action,
    strategy:wit-strategy
  }

  resource game-resource {
    new: static func(flop-card-str: string, mode: u8) -> game-resource;
    from-cache: static func(cache: list<u8>) -> result<game-resource, string>;
    action: func(action-num: u32) -> result<bool, string>;
    card-deal: func(card-str: string) -> result<bool, string>;
    get-range: func(player: u32) -> list<f32>;
    get-card-wights: func(player: u32) -> list<tuple<string, f32>>;
    get-node-info: func() -> list<f32>;
    get-board-cards: func() -> list<string>;
    get-available-action: func() -> list<wit-action>;
    get-card-index-from-str: func(card-str: string) -> result<u32, string>;
    get-history: func() -> list<u32>;
    get-valid-actions-history: func() -> list<wit-action-history-detail>;
    get-strategy: func() -> list<wit-strategy-map>;
    get-game-status: func() -> wit-game-status;
    apply-history: func(history: list<u32>) -> result<bool>;
    get-compressed-result: func() -> result<list<u8>, string>;
  }
}

world host {
  export game-manager;
}