package holdem-solver:host;

interface game-manager {
  enum board-state { flop, turn, river }
  enum game-status { chance, ip-action, oop-action, terminal }

  type wit-card = u32;
  /// Rust の `Action` に対応する variant
  variant wit-action {
    none,
    fold,
    check,
    call,
    bet(u32),
    raise(u32),
    all-in(u32),
    chance( wit-card ),
  }

  variant street {
    flop,
    turn,
    river,
  }

  record wit-action-ratio {
    action: wit-action,
    ratio: f32,
  }

  record wit-action-history-detail {
    action-ratio-list: list<wit-action-ratio>,
    player: u32,
    pot: u32,
    street: street,
  }

  record strategy {
    weight: f32,
    action-ratio: f32,
  }
  record strategy-map {
    hand: string,
    action: wit-action,
    strategy:strategy
  }

  resource game-resource {
    new: static func() -> game-resource;
    action: func(action-num: u32) -> result<bool, string>;
    card-deal: func(card-str: string) -> result<bool, string>;
    get-range: func(player: u32) -> list<f32>;
    get-card-wights: func(player: u32) -> list<tuple<string, f32>>;
    get-node-info: func() -> list<f32>;
    get-board-cards: func() -> list<string>;
    get-available-action: func() -> list<wit-action>;
    get-history: func() -> list<u32>;
    get-valid-actions-history: func() -> list<wit-action-history-detail>;
    get-strategy: func() -> list<strategy-map>;
    apply-history: func(history: list<u32>) -> result<bool>;
  }
}

world host {
  export game-manager;
}