package holdem-solver:host;

interface game-manager {
  resource game-resource {
    new: static func(number: u32) -> game-resource;
    write: func(number: u32);
    read: func() -> u32;
    up: func() -> u32;
    down: func() -> u32;
  }
}

world host {
  export game-manager;
}