// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod holdem_solver {
        pub mod host {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod game_manager {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum BoardState {
                    Flop,
                    Turn,
                    River,
                }
                impl ::core::fmt::Debug for BoardState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            BoardState::Flop => {
                                f.debug_tuple("BoardState::Flop").finish()
                            }
                            BoardState::Turn => {
                                f.debug_tuple("BoardState::Turn").finish()
                            }
                            BoardState::River => {
                                f.debug_tuple("BoardState::River").finish()
                            }
                        }
                    }
                }
                impl BoardState {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> BoardState {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => BoardState::Flop,
                            1 => BoardState::Turn,
                            2 => BoardState::River,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum WitGameStatus {
                    OopAction,
                    IpAction,
                    Chance,
                    Terminal,
                }
                impl ::core::fmt::Debug for WitGameStatus {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            WitGameStatus::OopAction => {
                                f.debug_tuple("WitGameStatus::OopAction").finish()
                            }
                            WitGameStatus::IpAction => {
                                f.debug_tuple("WitGameStatus::IpAction").finish()
                            }
                            WitGameStatus::Chance => {
                                f.debug_tuple("WitGameStatus::Chance").finish()
                            }
                            WitGameStatus::Terminal => {
                                f.debug_tuple("WitGameStatus::Terminal").finish()
                            }
                        }
                    }
                }
                impl WitGameStatus {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> WitGameStatus {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => WitGameStatus::OopAction,
                            1 => WitGameStatus::IpAction,
                            2 => WitGameStatus::Chance,
                            3 => WitGameStatus::Terminal,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                pub type WitCard = u32;
                /// Rust の `Action` に対応する variant
                #[derive(Clone, Copy)]
                pub enum WitAction {
                    None,
                    Fold,
                    Check,
                    Call,
                    Bet(u32),
                    Raise(u32),
                    AllIn(u32),
                    Chance(WitCard),
                }
                impl ::core::fmt::Debug for WitAction {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            WitAction::None => f.debug_tuple("WitAction::None").finish(),
                            WitAction::Fold => f.debug_tuple("WitAction::Fold").finish(),
                            WitAction::Check => {
                                f.debug_tuple("WitAction::Check").finish()
                            }
                            WitAction::Call => f.debug_tuple("WitAction::Call").finish(),
                            WitAction::Bet(e) => {
                                f.debug_tuple("WitAction::Bet").field(e).finish()
                            }
                            WitAction::Raise(e) => {
                                f.debug_tuple("WitAction::Raise").field(e).finish()
                            }
                            WitAction::AllIn(e) => {
                                f.debug_tuple("WitAction::AllIn").field(e).finish()
                            }
                            WitAction::Chance(e) => {
                                f.debug_tuple("WitAction::Chance").field(e).finish()
                            }
                        }
                    }
                }
                #[derive(Clone, Copy)]
                pub enum Street {
                    Flop,
                    Turn,
                    River,
                }
                impl ::core::fmt::Debug for Street {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Street::Flop => f.debug_tuple("Street::Flop").finish(),
                            Street::Turn => f.debug_tuple("Street::Turn").finish(),
                            Street::River => f.debug_tuple("Street::River").finish(),
                        }
                    }
                }
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct WitActionRatio {
                    pub action: WitAction,
                    pub ratio: f32,
                }
                impl ::core::fmt::Debug for WitActionRatio {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WitActionRatio")
                            .field("action", &self.action)
                            .field("ratio", &self.ratio)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct WitActionHistoryDetail {
                    pub action_ratio_list: _rt::Vec<WitActionRatio>,
                    pub game_status: WitGameStatus,
                    pub pot: u32,
                    pub street: Street,
                }
                impl ::core::fmt::Debug for WitActionHistoryDetail {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WitActionHistoryDetail")
                            .field("action-ratio-list", &self.action_ratio_list)
                            .field("game-status", &self.game_status)
                            .field("pot", &self.pot)
                            .field("street", &self.street)
                            .finish()
                    }
                }
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Strategy {
                    pub weight: f32,
                    pub action_ratio: f32,
                }
                impl ::core::fmt::Debug for Strategy {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Strategy")
                            .field("weight", &self.weight)
                            .field("action-ratio", &self.action_ratio)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct StrategyMap {
                    pub hand: _rt::String,
                    pub action: WitAction,
                    pub strategy: Strategy,
                }
                impl ::core::fmt::Debug for StrategyMap {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("StrategyMap")
                            .field("hand", &self.hand)
                            .field("action", &self.action)
                            .field("strategy", &self.strategy)
                            .finish()
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct GameResource {
                    handle: _rt::Resource<GameResource>,
                }
                type _GameResourceRep<T> = Option<T>;
                impl GameResource {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `GameResource`.
                    pub fn new<T: GuestGameResource>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _GameResourceRep<T> = Some(val);
                        let ptr: *mut _GameResourceRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestGameResource>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestGameResource>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestGameResource>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _GameResourceRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestGameResource>(&self) -> *mut _GameResourceRep<T> {
                        GameResource::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`GameResource`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct GameResourceBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a GameResource>,
                }
                impl<'a> GameResourceBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestGameResource>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _GameResourceRep<T> {
                        GameResource::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for GameResource {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]holdem-solver:host/game-manager"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]game-resource"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_static_game_resource_new_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: usize, arg2: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::new(_rt::string_lift(bytes0), arg2 as u8);
                    (result1).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_static_game_resource_from_cache_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::from_cache(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = (e).take_handle() as i32;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_static_game_resource_from_cache<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_action_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::action(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        arg1 as u32,
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match e {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_action<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_card_deal_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::card_deal(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match e {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_card_deal<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_range_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_range(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        arg1 as u32,
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_range<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 4, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_card_wights_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_card_wights(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        arg1 as u32,
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = result0;
                    let len4 = vec4.len();
                    let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec4.len() * (3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result4 = if layout4.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout4);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec4.into_iter().enumerate() {
                        let base = result4
                            .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t2_0, t2_1) = e;
                            let vec3 = (t2_0.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(t2_1);
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1.add(0).cast::<*mut u8>() = result4;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_card_wights<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_node_info_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_node_info(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_node_info<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 4, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_board_cards_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_board_cards(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = result0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = result3;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_board_cards<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_available_action_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_available_action(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = result0;
                    let len2 = vec2.len();
                    let layout2 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec2.len() * 8,
                        4,
                    );
                    let result2 = if layout2.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout2).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout2);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec2.into_iter().enumerate() {
                        let base = result2.add(i * 8);
                        {
                            match e {
                                WitAction::None => {
                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                }
                                WitAction::Fold => {
                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                }
                                WitAction::Check => {
                                    *base.add(0).cast::<u8>() = (2i32) as u8;
                                }
                                WitAction::Call => {
                                    *base.add(0).cast::<u8>() = (3i32) as u8;
                                }
                                WitAction::Bet(e) => {
                                    *base.add(0).cast::<u8>() = (4i32) as u8;
                                    *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::Raise(e) => {
                                    *base.add(0).cast::<u8>() = (5i32) as u8;
                                    *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::AllIn(e) => {
                                    *base.add(0).cast::<u8>() = (6i32) as u8;
                                    *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::Chance(e) => {
                                    *base.add(0).cast::<u8>() = (7i32) as u8;
                                    *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                }
                            }
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = result2;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_available_action<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 8, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_card_index_from_str_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::get_card_index_from_str(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(e);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_card_index_from_str<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_history_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_history(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_history<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 4, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_valid_actions_history_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_valid_actions_history(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (8 + 3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (8 + 3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let WitActionHistoryDetail {
                                action_ratio_list: action_ratio_list2,
                                game_status: game_status2,
                                pot: pot2,
                                street: street2,
                            } = e;
                            let vec4 = action_ratio_list2;
                            let len4 = vec4.len();
                            let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec4.len() * 12,
                                4,
                            );
                            let result4 = if layout4.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout4);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec4.into_iter().enumerate() {
                                let base = result4.add(i * 12);
                                {
                                    let WitActionRatio { action: action3, ratio: ratio3 } = e;
                                    match action3 {
                                        WitAction::None => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                        }
                                        WitAction::Fold => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                        }
                                        WitAction::Check => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                        }
                                        WitAction::Call => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                        }
                                        WitAction::Bet(e) => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                            *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                        }
                                        WitAction::Raise(e) => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                            *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                        }
                                        WitAction::AllIn(e) => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                            *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                        }
                                        WitAction::Chance(e) => {
                                            *base.add(0).cast::<u8>() = (7i32) as u8;
                                            *base.add(4).cast::<i32>() = _rt::as_i32(e);
                                        }
                                    }
                                    *base.add(8).cast::<f32>() = _rt::as_f32(ratio3);
                                }
                            }
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(0).cast::<*mut u8>() = result4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (game_status2.clone() as i32) as u8;
                            *base
                                .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(pot2);
                            match street2 {
                                Street::Flop => {
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                                Street::Turn => {
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                Street::River => {
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                }
                            }
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_valid_actions_history<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base5 = l0;
                    let len5 = l1;
                    for i in 0..len5 {
                        let base = base5
                            .add(i * (8 + 3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base4 = l2;
                            let len4 = l3;
                            _rt::cabi_dealloc(base4, len4 * 12, 4);
                        }
                    }
                    _rt::cabi_dealloc(
                        base5,
                        len5 * (8 + 3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_strategy_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_strategy(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let StrategyMap {
                                hand: hand2,
                                action: action2,
                                strategy: strategy2,
                            } = e;
                            let vec3 = (hand2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            match action2 {
                                WitAction::None => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                                WitAction::Fold => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                WitAction::Check => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                }
                                WitAction::Call => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (3i32) as u8;
                                }
                                WitAction::Bet(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (4i32) as u8;
                                    *base
                                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::Raise(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (5i32) as u8;
                                    *base
                                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::AllIn(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (6i32) as u8;
                                    *base
                                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i32>() = _rt::as_i32(e);
                                }
                                WitAction::Chance(e) => {
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (7i32) as u8;
                                    *base
                                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i32>() = _rt::as_i32(e);
                                }
                            }
                            let Strategy {
                                weight: weight4,
                                action_ratio: action_ratio4,
                            } = strategy2;
                            *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(weight4);
                            *base
                                .add(12 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(action_ratio4);
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_strategy<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_game_status_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_game_status(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_apply_history_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let result1 = T::apply_history(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2.add(1).cast::<u8>() = (match e {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(_) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_resource_get_compressed_result_cabi<
                    T: GuestGameResource,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_compressed_result(
                        unsafe { GameResourceBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_resource_get_compressed_result<
                    T: GuestGameResource,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                pub trait Guest {
                    type GameResource: GuestGameResource;
                }
                pub trait GuestGameResource: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]holdem-solver:host/game-manager"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]game-resource"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]holdem-solver:host/game-manager"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]game-resource"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new(flop_card_str: _rt::String, mode: u8) -> GameResource;
                    fn from_cache(
                        cache: _rt::Vec<u8>,
                    ) -> Result<GameResource, _rt::String>;
                    fn action(&self, action_num: u32) -> Result<bool, _rt::String>;
                    fn card_deal(
                        &self,
                        card_str: _rt::String,
                    ) -> Result<bool, _rt::String>;
                    fn get_range(&self, player: u32) -> _rt::Vec<f32>;
                    fn get_card_wights(
                        &self,
                        player: u32,
                    ) -> _rt::Vec<(_rt::String, f32)>;
                    fn get_node_info(&self) -> _rt::Vec<f32>;
                    fn get_board_cards(&self) -> _rt::Vec<_rt::String>;
                    fn get_available_action(&self) -> _rt::Vec<WitAction>;
                    fn get_card_index_from_str(
                        &self,
                        card_str: _rt::String,
                    ) -> Result<u32, _rt::String>;
                    fn get_history(&self) -> _rt::Vec<u32>;
                    fn get_valid_actions_history(
                        &self,
                    ) -> _rt::Vec<WitActionHistoryDetail>;
                    fn get_strategy(&self) -> _rt::Vec<StrategyMap>;
                    fn get_game_status(&self) -> WitGameStatus;
                    fn apply_history(&self, history: _rt::Vec<u32>) -> Result<bool, ()>;
                    fn get_compressed_result(&self) -> Result<_rt::Vec<u8>, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_holdem_solver_host_game_manager_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[static]game-resource.new")]
                        unsafe extern "C" fn export_static_game_resource_new(arg0 : * mut
                        u8, arg1 : usize, arg2 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_static_game_resource_new_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0, arg1,
                        arg2) } } #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[static]game-resource.from-cache")]
                        unsafe extern "C" fn export_static_game_resource_from_cache(arg0
                        : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_static_game_resource_from_cache_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[static]game-resource.from-cache")]
                        unsafe extern "C" fn
                        _post_return_static_game_resource_from_cache(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_static_game_resource_from_cache::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.action")]
                        unsafe extern "C" fn export_method_game_resource_action(arg0 : *
                        mut u8, arg1 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_action_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.action")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_action(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_action::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.card-deal")]
                        unsafe extern "C" fn export_method_game_resource_card_deal(arg0 :
                        * mut u8, arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_game_resource_card_deal_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1, arg2) }
                        } #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.card-deal")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_card_deal(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_card_deal::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-range")]
                        unsafe extern "C" fn export_method_game_resource_get_range(arg0 :
                        * mut u8, arg1 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_game_resource_get_range_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-range")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_range(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_range::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-card-wights")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_card_wights(arg0 : * mut u8, arg1
                        : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_card_wights_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1) } }
                        #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-card-wights")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_card_wights(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_card_wights::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-node-info")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_node_info(arg0 : * mut u8,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_node_info_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-node-info")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_node_info(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_node_info::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-board-cards")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_board_cards(arg0 : * mut u8,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_board_cards_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-board-cards")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_board_cards(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_board_cards::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-available-action")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_available_action(arg0 : * mut
                        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_available_action_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-available-action")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_available_action(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_available_action::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-card-index-from-str")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_card_index_from_str(arg0 : * mut
                        u8, arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_game_resource_get_card_index_from_str_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0, arg1,
                        arg2) } } #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-card-index-from-str")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_card_index_from_str(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_card_index_from_str::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0) } }
                        #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-history")]
                        unsafe extern "C" fn export_method_game_resource_get_history(arg0
                        : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_history_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-history")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_history(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_history::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-valid-actions-history")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_valid_actions_history(arg0 : *
                        mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_valid_actions_history_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-valid-actions-history")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_valid_actions_history(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_valid_actions_history::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0) } }
                        #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-strategy")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_strategy(arg0 : * mut u8,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_strategy_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-strategy")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_strategy(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_strategy::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-game-status")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_game_status(arg0 : * mut u8,) ->
                        i32 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_game_status_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.apply-history")]
                        unsafe extern "C" fn
                        export_method_game_resource_apply_history(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_game_resource_apply_history_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0, arg1, arg2) }
                        } #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[method]game-resource.get-compressed-result")]
                        unsafe extern "C" fn
                        export_method_game_resource_get_compressed_result(arg0 : * mut
                        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_resource_get_compressed_result_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::GameResource > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_holdem-solver:host/game-manager#[method]game-resource.get-compressed-result")]
                        unsafe extern "C" fn
                        _post_return_method_game_resource_get_compressed_result(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_resource_get_compressed_result::<<$ty
                        as $($path_to_types)*:: Guest >::GameResource > (arg0) } } const
                        _ : () = { #[doc(hidden)] #[unsafe (export_name =
                        "holdem-solver:host/game-manager#[dtor]game-resource")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: GameResource::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::GameResource > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_holdem_solver_host_game_manager_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_host_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::holdem_solver::host::game_manager::__export_holdem_solver_host_game_manager_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::holdem_solver::host::game_manager);
    };
}
#[doc(inline)]
pub(crate) use __export_host_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:holdem-solver:host:host:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1619] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x0b\x01A\x02\x01\
A\x02\x01BD\x01m\x03\x04flop\x04turn\x05river\x04\0\x0bboard-state\x03\0\0\x01m\x04\
\x0aoop-action\x09ip-action\x06chance\x08terminal\x04\0\x0fwit-game-status\x03\0\
\x02\x01y\x04\0\x08wit-card\x03\0\x04\x01q\x08\x04none\0\0\x04fold\0\0\x05check\0\
\0\x04call\0\0\x03bet\x01y\0\x05raise\x01y\0\x06all-in\x01y\0\x06chance\x01\x05\0\
\x04\0\x0awit-action\x03\0\x06\x01q\x03\x04flop\0\0\x04turn\0\0\x05river\0\0\x04\
\0\x06street\x03\0\x08\x01r\x02\x06action\x07\x05ratiov\x04\0\x10wit-action-rati\
o\x03\0\x0a\x01p\x0b\x01r\x04\x11action-ratio-list\x0c\x0bgame-status\x03\x03pot\
y\x06street\x09\x04\0\x19wit-action-history-detail\x03\0\x0d\x01r\x02\x06weightv\
\x0caction-ratiov\x04\0\x08strategy\x03\0\x0f\x01r\x03\x04hands\x06action\x07\x08\
strategy\x10\x04\0\x0cstrategy-map\x03\0\x11\x04\0\x0dgame-resource\x03\x01\x01i\
\x13\x01@\x02\x0dflop-card-strs\x04mode}\0\x14\x04\0\x19[static]game-resource.ne\
w\x01\x15\x01p}\x01j\x01\x14\x01s\x01@\x01\x05cache\x16\0\x17\x04\0\x20[static]g\
ame-resource.from-cache\x01\x18\x01h\x13\x01j\x01\x7f\x01s\x01@\x02\x04self\x19\x0a\
action-numy\0\x1a\x04\0\x1c[method]game-resource.action\x01\x1b\x01@\x02\x04self\
\x19\x08card-strs\0\x1a\x04\0\x1f[method]game-resource.card-deal\x01\x1c\x01pv\x01\
@\x02\x04self\x19\x06playery\0\x1d\x04\0\x1f[method]game-resource.get-range\x01\x1e\
\x01o\x02sv\x01p\x1f\x01@\x02\x04self\x19\x06playery\0\x20\x04\0%[method]game-re\
source.get-card-wights\x01!\x01@\x01\x04self\x19\0\x1d\x04\0#[method]game-resour\
ce.get-node-info\x01\"\x01ps\x01@\x01\x04self\x19\0#\x04\0%[method]game-resource\
.get-board-cards\x01$\x01p\x07\x01@\x01\x04self\x19\0%\x04\0*[method]game-resour\
ce.get-available-action\x01&\x01j\x01y\x01s\x01@\x02\x04self\x19\x08card-strs\0'\
\x04\0-[method]game-resource.get-card-index-from-str\x01(\x01py\x01@\x01\x04self\
\x19\0)\x04\0![method]game-resource.get-history\x01*\x01p\x0e\x01@\x01\x04self\x19\
\0+\x04\0/[method]game-resource.get-valid-actions-history\x01,\x01p\x12\x01@\x01\
\x04self\x19\0-\x04\0\"[method]game-resource.get-strategy\x01.\x01@\x01\x04self\x19\
\0\x03\x04\0%[method]game-resource.get-game-status\x01/\x01j\x01\x7f\0\x01@\x02\x04\
self\x19\x07history)\00\x04\0#[method]game-resource.apply-history\x011\x01j\x01\x16\
\x01s\x01@\x01\x04self\x19\02\x04\0+[method]game-resource.get-compressed-result\x01\
3\x04\0\x1fholdem-solver:host/game-manager\x05\0\x04\0\x17holdem-solver:host/hos\
t\x04\0\x0b\x0a\x01\0\x04host\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
